### ISSUE TITLE
Compile-time errors related to `this` are gone

### ISSUE THREAD

**Issue by karol-majewski** [unsplash/pipe-ts#6]
Let's suppose I have a function that uses `this` other than `Window`. In this example, I have a static method that _must_ be called with `this` of `JSON`.

```ts
declare class JSON {
  /**
   * `parse` should always be called with `this === JSON`.
   */
  static parse(this: JSON, input: string): object;
}

const { parse } = JSON;

JSON.parse('1'); // Good
parse('1') // Bad, we get a compile-time error as expected
```

TypeScript will warn you when you try and call `parse` as if it were a standalone function.

However, when we do the same thing with `pipe`/`pipeWith`, the error is gone.

```ts
pipeWith(
  'foo',
  JSON.parse // Good: `parse` is called with `this` of JSON
)

pipeWith(
  'foo',
  parse // Bad: this should give us a compile-time error!
)
```

**Comment by OliverJAsh** [comment]
Good catch. Is there anything we can do to prevent these mistakes? My guess is there's not, since the function is just being passed as a value—TypeScript doesn't know how/when `pipeWith` will use that function. IIRC there are lint rules to help catch mistakes like this.

P.S. in your first example…

```ts
pipeWith(
  'foo',
  JSON.parse
)
```

…  `parse` is not called with `this` of JSON.

**Comment by karol-majewski** [comment]
> … `parse` is _not_ called with `this` of `JSON`.

You're absolutely right, the correct way to call it would be without point-free style, e.g. `arg => JSON.parse(arg)`.

**Comment by karol-majewski** [comment]
If functions dependent on `this` cannot be used with `pipe`, we can reject them in compile-time:

```ts
function pipeWith<A, B>(a: A, ab: (this: void, a: A) => B): B
```

This makes it type-safe.

```ts
JSON.parse('1');                         // ✅ Works
parse('1');                              // ✅ Compile-time error
            
pipeWith('foo', JSON.parse);             // ✅ Compile-time error
pipeWith('foo', parse);                  // ✅ Compile-time error
pipeWith('foo', JSON.parse);             // ✅ Compile-time error
pipeWith('foo', arg => JSON.parse(arg)); // ✅ Works
```

[TypeScript Playground](https://www.typescriptlang.org/play/?ssl=20&ssc=52&pln=14&pc=1#code/GYVwdgxgLglg9mABABxsgpgdRlAFgHgEEAaRAIQD4AKAQwC5ETEaAjBqvGAZwYDc4YAE1L1GASkQBeCuTEMyiAN4AoRGsQAndFBAakrWmIDcygL7Llg9BAA2NLYls0uXRACkAygHkAcktWIAPQAVMEBiMGIAAbI9lzoUYhcuHAgNoLMNgDuNACerizojjQ2NugZWTi40ZyukvXu3j5RAHThwYEBXFA0sBAocegcuNwMnr6kMGDIIFAM3RpTAOZyiHAsAFbWUCbmyhAI3UoDGvGIplKNvibK4z4tsadDAOQAjM-G6l-fP7+BgYhAKDkiEwcA0AGsuMpHvEqG8PkZfkjkT9-kDEABhOAAW1QZQAtLBsUV0BoNGDwsjoWgsFU4cA4HBnqQ7g9Bp8UWo0cCsbiYASiSSyRTUBhsHh6YzmSd4hzOd9uZicXj0ISYMTEKTyRpqWK6c8GUyWU02U85SjFbyVWqNVqRTTxbhJUbmBollIZKyYUN7CtPorQRCocp0AAPZBgqDHUxAA)

**Comment by OliverJAsh** [comment]
Nice! Let's do that

**Comment by OliverJAsh** [comment]
@karol-majewski I just realised, your example of `JSON.parse` above doesn't work with the default types of `JSON.parse` 😢

**Comment by OliverJAsh** [comment]
In hindsight, isn't this better handled with something like https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/unbound-method.md?

IIUC, the benefit the lint rule has over the changes made by this PR is that it will catch mistakes for methods where `this` is not explicitly defined, e.g. class methods:

```ts
class Foo {
  bar(key: string) {
    return key;
  }
}

const foo = new Foo();
// No type error here ❌ 
// ESLint error here ✅ 
const result = pipeWith('foo', foo.bar);
```

**Comment by karol-majewski** [comment]
That's right — the snippet in the original post was using a different definition. 

[A version that is closer to how global constructors are defined.](https://www.typescriptlang.org/play/?ts=3.8.0-dev.20200107#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcsCQB1LDACwB4BBAGngCEA+ACigC54H4oAjbmypYAztwBuOLMEZceASngBeFswXcmAbgBQOrKgwgYiKGAQApAMoB5AHLwA3jviv4AegBUnl2-if4AAMCWFEQQPhRShxkCGA+CAB3KABPUXh+BDAoCAgQeMSKSiCRdOVy+Gt7QIA6XzdPd3rCUJBhSjFuKrtGIwAPDG5RDBgDAHNGOAksCWMAfiFS7ihUFMYAaxAUoZHxxgkc5BBl1aVVPlOTlN0AXz1QSFgEA5hK2zsu990dMDxhpxaMDC8BuKje9m+3RqISBbQA5ABGOEKLR+NHojFudzueCAUHJ4KQcDB1qIdDCwmxEcjUZjaXTXNi8fAAMI4AC2RDyAFpsGyEMYYES9EQSOQqJTEDgcHDGFDySAUfSGTj8ayOVhubz+TBBTAycQyEUJVKZYCwoqlWjGar2ZyQDysHz4AKhSLDeK4ZLpXIYGMVGo5a0OL6FIrrQSiSS9CA+gQiRgnDcgA)


Not everyone is using ESLint. It would be best if such an error came from the right place — the type checker itself. Perhaps it's worth seeing if the standard library types can be changed in a way that requires a specific `this`.

```diff
 interface JSON {
-    parse(text: string, reviver?: (this: any, key: string, value: any) => any): any;
+    parse(this: JSON, text: string, reviver?: (this: any, key: string, value: any) => any): any;
 }
```

Have you tried using this rule? I tried using [its TSLint cousin](https://palantir.github.io/tslint/rules/no-unbound-method/) and it didn't cover all cases. These two didn't raise an error (they should):

```ts
parse('1'); // No error (expected one)                   
pipeWith('foo', parse); // No error (expected one)                   
```

**Comment by OliverJAsh** [comment]
> Perhaps it's worth seeing if the standard library types can be changed in a way that requires a specific `this`.

That could help, although note that in the specific example of `JSON.parse`, it does work with any `this`:

```ts
const { parse } = JSON;
parse('{ "foo": 1 }') // => { foo: 1 }
```

This makes me wonder why TypeScript doesn't prescribe a `this` type automatically for class methods, e.g.

```ts
class Foo {
  value = 2
  add(number: number) {
    return this.value + number;
  }
}

const foo = new Foo();
// No type error here because `foo.add` doesn't have an *explicit*` this type ❌ 
const result = pipeWith(1, foo.add);
```

It would be very annoying to manually type `this` every time, for every method on every class!

```diff
-  add(number: number) {
+  add(this: Foo, number: number) {
```

IMO this shouldn't be necessary because TypeScript clearly knows the type of `this` already as we're using it inside the method implementation. I wonder if this has been considered by the TS team?

Unless consumers are very careful to manually + explicitly annotate the `this` type, they won't get any type errors when trying to use `pipe`/`pipeWith`.

> Have you tried using this rule? I tried using [its TSLint cousin](https://palantir.github.io/tslint/rules/no-unbound-method/) and it didn't cover all cases. These two didn't raise an error (they should):

I used the TSLint rule a long time ago and it seemed to be useful. Yesterday I played with the ESLint variant here: https://github.com/unsplash/unsplash-web/pull/4467. I think the ESLint rule has the same problem though: https://github.com/typescript-eslint/typescript-eslint/issues/1112.

**Comment by karol-majewski** [comment]
> IMO this shouldn't be necessary because TypeScript clearly knows the type of `this` already as we're using it inside the method implementation. I wonder if this has been considered by the TS team?

Exactly — it would be safe to implicitly apply a `this` equal to the class instance for non-static methods. As far as I know, `this` in methods is used by the community only to achieve [f-bounded polymorphism](https://github.com/Microsoft/TypeScript/issues/13852#issuecomment-290941826), which is a fancy name for telling when a method can be called based on the provided type argument.

```ts
interface Collection<T> {
  // This methods is available for any T.
  toArray(): T[]; 

  // This method is only available for array types, where T is a number
  sum(this: Collection<number>): number;
}

declare const strings: Collection<string>
declare const numbers: Collection<number>

strings.sum(); // Compile-time error
numbers.sum(); // OK
```

But since `Collection<number>` is covariant in relation to `T`, I don't see why applying an implicit `this` better than `any` would cause problems. I'm sure they had good reasons to do it this way, though.

> That could help, although note that in the specific example of `JSON.parse`, it does work with any `this`:

In this specific example, yes, but it's easy to find an example where it doesn't:

```ts
const { getItem } = localStorage;

getItem('foo'); // Runtime exception
```

**Comment by OliverJAsh** [comment]
> I'm sure they had good reasons to do it this way, though.

Let's find out: https://github.com/microsoft/TypeScript/issues/36100 🍿

**Comment by OliverJAsh** [comment]
Sounds like they don't do it for performance reasons https://github.com/microsoft/TypeScript/issues/35451

Off the back of the discussion in https://github.com/typescript-eslint/typescript-eslint/pull/1279, I'm convinced this should be left to a lint rule.

For this to work:

1. all class methods must have `this: this` *and*
2. all higher-order functions (not just `pipe` and `pipeWith` but everything else such as `addEventListener`) that may receive class methods as a parameter must have `this: void`.

It doesn't hurt to keep `this: void` in `pipe` and `pipeWith`, but we're never going to really benefit from it, given that nearly the class methods we use will not carry their `this` type. We can fix that where we define the types, but that would rely on a lot of discipline, and a lot of the time it's outside of our control (i.e. third party types). For that reason, perhaps we should revert this change and use lint rules instead, which will not only address this use case (`pipe` and `pipeWith`) but also all other usages of higher-order functions.

**Comment by karol-majewski** [comment]
I don't think there's any harm in keeping it for the benefit of users who _do_ make the effort and type their methods deliberately?

Example: the Snowplow collector requires a `this` of `TrackersByNamespace`.

```ts
declare const trackers: Snowplow.TrackersByNamespace;

declare global {
  interface Window {
    snowplow: {
      (callback: (this: TrackersByNamespace) => void): void;
    }
  }
}

pipeWith(
  trackers,
  window.snowplow,
);
```

If we lift that requirement from `pipeWith`, the type error will be gone.
