### ISSUE TITLE
broken reference in source map

### ISSUE THREAD

**Issue by kruschid** [unsplash/pipe-ts#8]
I get a warning whenever I try to transpile my project with parcel:

```
Could not load source file "../src/index.ts" in source map of "../node_modules/pipe-ts/target/index.js".
```

It seems that the source map has a reference to a file that was excluded (see `files` property in `package.json`) from publishing. It would be cool if the owner of this module provide an update,  since I'm not allowed to update the npm package directly. 👍

**Comment by OliverJAsh** [comment]
Thanks for filing! Fixed in https://github.com/unsplash/pipe-ts/releases/tag/v0.0.9
